Added support for missing display or no zenity

diff --git a/actions b/actions
--- a/actions
+++ b/actions
@@ -6,6 +6,18 @@ currVersion=$(uname -r | sed 's/-.*/ /g')
 display=$(w -oush | grep -Eo ' :[0-9]+' | uniq | cut -d \  -f 2)
 user=$(w -oush | grep "$display" | awk '{print $1}' | head -n 1)
 
+zenityWindow() {
+  if ! which zenity > /dev/null 2>&1; then
+    echo "Zenity not installed, it is required for graphical menus"
+    return 1
+  fi
+  if [ $display == "" ]; then
+    echo "No display available"
+    return 1
+  fi
+  #Set a variable with zenity output if it had an input window
+}
+
 installKernel() {
   if cat /etc/*-release |grep -q Raspbian 2>&1 ; then
     echo "Raspbian / Raspberry Pis are not supported with this feature"
@@ -66,58 +78,65 @@ installKernel() {
 
   declare -a packages=("https://kernel.ubuntu.com/~kernel-ppa/mainline/v$installVersionLink/linux-headers-$installVersion-$installVersionShort""_$installVersion-$installVersionShort.$kernelDate""_all.deb" "https://kernel.ubuntu.com/~kernel-ppa/mainline/v$installVersionLink/linux-headers-$installVersion-$installVersionShort-generic_$installVersion-$installVersionShort.$kernelDate""_$(dpkg --print-architecture).deb" "https://kernel.ubuntu.com/~kernel-ppa/mainline/v$installVersionLink/linux-modules-$installVersion-$installVersionShort-generic_$installVersion-$installVersionShort.$kernelDate""_$(dpkg --print-architecture).deb" "https://kernel.ubuntu.com/~kernel-ppa/mainline/v$installVersionLink/linux-image-unsigned-$installVersion-$installVersionShort-generic_$installVersion-$installVersionShort.$kernelDate""_$(dpkg --print-architecture).deb")
 
-  ( echo "Downloading kernel version $installVersion..." 1>&2 && echo "" 1>&2
-  if [ ! -d "/tmp/kernel-notify" ]; then
-    mkdir /tmp/kernel-notify
-  fi
-  cd /tmp/kernel-notify
-
-  for filename in "${packages[@]}"; do
-    let progress=$progress+20
-    echo "# Downloading ${filename##*/}..."
-    curl -O $filename
-    echo "$progress"
-    filename="${filename##*/}"
-    installList="$installList $filename"
-    if ! file $filename | grep -q 'Debian binary package'; then
-      echo "$filename: Not a Debian package" 1>&2
-      clearFiles "$installList"
-      exit
+  dpkgKernelInstall() {
+    echo "Downloading kernel version $installVersion..." 1>&2 && echo "" 1>&2
+    if [ ! -d "/tmp/kernel-notify" ]; then
+      mkdir /tmp/kernel-notify
     fi
-  done
+    cd /tmp/kernel-notify
 
-  echo "# Downloading & verifying checksums..."
-  curl -O "https://kernel.ubuntu.com/~kernel-ppa/mainline/v$installVersionLink/CHECKSUMS"
-  echo "90"
-  if ! sha256sum --ignore-missing -c CHECKSUMS 1>&2; then
-    echo "Downloaded kernel checksum invalid" 1>&2
-    clearFiles "$installList CHECKSUMS"
-  fi
-  echo "99"
+    for filename in "${packages[@]}"; do
+      let progress=$progress+20
+      echo "# Downloading ${filename##*/}..."
+      curl -O $filename
+      echo "$progress"
+      filename="${filename##*/}"
+      installList="$installList $filename"
+      if ! file $filename | grep -q 'Debian binary package'; then
+        echo "$filename: Not a Debian package" 1>&2
+        clearFiles "$installList"
+        exit
+      fi
+    done
 
-  echo "" 1>&2; echo "All packages verified, installing kernel version $installVersion..." 1>&2
-  checkDpkg
+    echo "# Downloading & verifying checksums..."
+    curl -O "https://kernel.ubuntu.com/~kernel-ppa/mainline/v$installVersionLink/CHECKSUMS"
+    echo "90"
+    if ! sha256sum --ignore-missing -c CHECKSUMS 1>&2; then
+      echo "Downloaded kernel checksum invalid" 1>&2
+      clearFiles "$installList CHECKSUMS"
+    fi
+    echo "99"
 
-  progress=0
-  echo "$progress"
-  read -ra installArray <<< $installList
-  for filename in "${installArray[@]}"; do
-    let progress=$progress+25
-    echo "# Installing ${filename##*/}..."
-    sudo dpkg -i $filename 1>&2
+    echo "" 1>&2; echo "All packages verified, installing kernel version $installVersion..." 1>&2
+    checkDpkg
+
+    progress=0
     echo "$progress"
-  done
-  echo "# Installed Kernel v$installVersion"
-  echo "Done, reboot for the update to take effect" 1>&2
+    read -ra installArray <<< $installList
+    for filename in "${installArray[@]}"; do
+      let progress=$progress+25
+      echo "# Installing ${filename##*/}..."
+      sudo dpkg -i $filename 1>&2
+      echo "$progress"
+    done
+    echo "# Installed Kernel v$installVersion"
+    echo "Done, reboot for the update to take effect" 1>&2
+    clearFiles "$installList CHECKSUMS"
+  }
 
-  clearFiles "$installList CHECKSUMS") |
-  sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $user)/bus zenity --progress --auto-close \
+  if ! zenityWindow; then
+    echo "Zenity not supported"
+    dpkgKernelInstall
+  else
+    dpkgKernelInstall | sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $user)/bus zenity --progress --auto-close \
     --window-icon="/usr/share/kernel-notify/icon.png" \
     --title="Kernel Updater" \
     --text="Starting update..." \
     --width=400 \
     --height=100 \
     --percentage=0
+  fi
 
   if [ "$?" == "1" ]; then
     echo "Cancelled"
