Fix program crashing if no network can be found

diff --git a/kernel-notify b/kernel-notify
--- a/kernel-notify
+++ b/kernel-notify
@@ -158,8 +158,18 @@ sendNotification() {
   fi
 }
 
-echo "Checking latest version..."
-latestVersion=$(echo $(curl -k https://www.kernel.org -s) | tr -d '\n' | awk -F'<td id="latest_button">' '{print $2}' | cut -c -70 | tr -d '\n' | awk -F'/' '{print $8}' | cut -c -70 | sed 's/linux-//g' | sed 's/.t.*//g')
+echo -n "Checking latest version..."
+latestVersion=$(echo $(curl -k htps://www.kernel.org -s) | tr -d '\n' | awk -F'<td id="latest_button">' '{print $2}' | cut -c -70 | tr -d '\n' | awk -F'/' '{print $8}' | cut -c -70 | sed 's/linux-//g' | sed 's/.t.*//g')
+if [ "$latestVersion" == "" ]; then
+  sleep 0.5; echo -ne "\rChecking latest version... Error\n"; sleep 0.5
+  latestVersion="x.x.x"
+  if [ "$1" == "-a" ] || [ "$1" == "--add-kernel" ] || [ "$1" == "-aa" ]; then
+    echo "Likely a network error, action cancelled"
+    exit
+  fi
+else
+  echo ""
+fi
 
 read -ra args <<< $@
 if [ "$1" == "-c" ] || [ "$1" == "--config" ]; then
@@ -192,6 +202,9 @@ currVersionFull=$currVersion
 echo 'Latest Kernel: '$latestVersionFull
 echo 'Current Kernel: '$currVersionFull
 
+if [ "$latestVersion" == "x.x.x" ]; then
+  exit 1
+fi
 latestVersion=$(echo "${latestVersion//.}")
 
 if [ "$latestVersion" -le "99" ]; then
