Cleaned up debian helper scripts

diff --git a/src/debian/DEBIAN/postinst b/src/debian/DEBIAN/postinst
--- a/src/debian/DEBIAN/postinst
+++ b/src/debian/DEBIAN/postinst
@@ -1,9 +1,7 @@
 #!/bin/bash
 
 #Remove notifications if unsupported
-if [ ! "$(arch)" == "x86_64" ]; then
-  rm /usr/share/kernel-notify/notifications
-fi
+if [ ! "$(arch)" == "x86_64" ]; then rm /usr/share/kernel-notify/notifications; fi
 
 #Config updater
 if [ -f /usr/share/kernel-notify/config.old ] && ! diff /usr/share/kernel-notify/config /usr/share/kernel-notify/config.old > /dev/null; then
@@ -20,22 +18,17 @@ if [ -f /usr/share/kernel-notify/config.old ] && ! diff /usr/share/kernel-notify
     echo -n "Replacing deprecated config values with replacements..."
     oldConfig="$(cat /usr/share/kernel-notify/config)"
     oldConfig="${oldConfig//'"0"'/'"false"'}"
-    oldConfig="${oldConfig//'"1"'/'"true"'}"
-    echo "$oldConfig" > /usr/share/kernel-notify/config
-    echo " Done"
+    oldConfig="${oldConfig//'"1"'/'"true"'}"﻿
+    echo "$oldConfig" > /usr/share/kernel-notify/config; echo " Done"
   fi
 fi
 
 if [[ -f "/tmp/remove-kernel-notify-autostart" ]]; then
-  rm "/tmp/remove-kernel-notify-autostart"
-  if [[ -f "/etc/xdg/autostart/kernel-notify.desktop" ]]; then
-    rm "/etc/xdg/autostart/kernel-notify.desktop"
-  fi
+  rm -f "/tmp/remove-kernel-notify-autostart" "/etc/xdg/autostart/kernel-notify.desktop"
 fi
 
 if kernel-notify -v; then
   echo ""; echo "Successfully installed kernel-notify"
 else
-  echo ""; echo "  ATTENTION: Installing kernel-notify failed"
-  exit 1
+  echo ""; echo "  ATTENTION: Installing kernel-notify failed"; exit 1
 fi
